"""
Formatter module for Crypto Morning Pulse Bot.
Handles Discord embed formatting and message composition.
"""

from typing import List, Dict, Optional
from datetime import datetime
import discord

from src.config import (
    EMBED_COLOR,
    TIMEZONE,
)
from src.logger import logger


class DiscordFormatter:
    """Formats content into Discord embeds and messages."""
    
    # Category display names (Chinese)
    CATEGORY_NAMES = {
        "macro_policy": "Macro/Policy",
        "capital_flow": "Capital Flow",
        "major_coins": "Major Coins",
        "altcoins_trending": "Altcoins/Trending",
        "tech_narratives": "Tech/Narratives",
        "kol_insights": "KOL Insights",
    }
    
    @staticmethod
    def create_daily_briefing_embed(
        items: List[Dict],
        degraded_mode: bool = False
    ) -> discord.Embed:
        """
        Create a Discord embed for the daily crypto briefing.
        
        Args:
            items: List of selected news/KOL items to include.
            degraded_mode: Whether to include degradation warning.
        
        Returns:
            discord.Embed: Formatted Discord embed.
        """
        # Create embed with title and basic info
        now = datetime.now()
        date_str = now.strftime("%b %d, %Y")
        
        embed = discord.Embed(
            title=f"🌅 Crypto Morning Pulse | {date_str}",
            description="Here's what's moving markets today",
            color=EMBED_COLOR,
            timestamp=now
        )
        
        # Add separator line
        embed.add_field(
            name="━━━━━━━━━━━━━━━━━━━━━━━━━",
            value="",
            inline=False
        )
        
        # Add items as fields
        for idx, item in enumerate(items, 1):
            category = item.get("category", "macro_policy")
            category_display = DiscordFormatter.CATEGORY_NAMES.get(category, "News")
            
            # Get rewritten summary (improved content)
            summary = item.get("summary_rewritten", item.get("summary", ""))
            
            # Get source link and name
            source_url = item.get("url", "")
            source_name = item.get("source_name", item.get("source", "Unknown"))
            
            # Build field value: Category + Summary + Source
            field_value = f"**{category_display}:** {summary}"
            
            # Add source link if available
            if source_url:
                field_value += f"\n**[{source_name}]({source_url})**"
            
            # Add field to embed with numbering
            embed.add_field(
                name=f"{idx}.",
                value=field_value,
                inline=False
            )
        
        # Add separator line before footer
        embed.add_field(
            name="━━━━━━━━━━━━━━━━━━━━━━━━━",
            value="",
            inline=False
        )
        
        # Add footer with data sources
        embed.set_footer(
            text="Powered by Manus AI | Data: X, CryptoPanic, CoinGecko"
        )
        
        # Add image if available (set as embed image for the last item)
        if items and items[-1].get("image_url"):
            embed.set_image(url=items[-1].get("image_url"))
        
        return embed
    
    @staticmethod
    def create_health_check_embed(
        status: Dict,
        degraded: bool = False
    ) -> discord.Embed:
        """
        Create a health check status embed.
        
        Args:
            status: Status information dictionary.
            degraded: Whether system is in degraded mode.
        
        Returns:
            discord.Embed: Formatted health check embed.
        """
        now = datetime.now()
        
        color = 0xFF6B6B if degraded else 0x51CF66  # Red for degraded, green for healthy
        
        embed = discord.Embed(
            title="🏥 Crypto Morning Pulse - Health Check",
            description="Daily system status report",
            color=color,
            timestamp=now
        )
        
        # Add status fields
        embed.add_field(
            name="Status",
            value="⚠️ Degraded Mode" if degraded else "✅ Healthy",
            inline=False
        )
        
        embed.add_field(
            name="Items Processed",
            value=str(status.get("items_processed", 0)),
            inline=True
        )
        
        embed.add_field(
            name="Items Published",
            value=str(status.get("items_published", 0)),
            inline=True
        )
        
        if status.get("errors"):
            embed.add_field(
                name="Errors",
                value=status.get("errors"),
                inline=False
            )
        
        embed.set_footer(
            text="Generated by Crypto Morning Pulse Bot"
        )
        
        return embed
    
    @staticmethod
    def create_error_notification_embed(
        error_message: str,
        error_count: int = 1
    ) -> discord.Embed:
        """
        Create an error notification embed.
        
        Args:
            error_message: Error message to display.
            error_count: Number of consecutive errors.
        
        Returns:
            discord.Embed: Formatted error embed.
        """
        now = datetime.now()
        
        embed = discord.Embed(
            title="🚨 Crypto Morning Pulse - Error Alert",
            description=f"Error occurred during daily briefing generation",
            color=0xFF6B6B,  # Red
            timestamp=now
        )
        
        embed.add_field(
            name="Error",
            value=error_message[:1024],
            inline=False
        )
        
        embed.add_field(
            name="Consecutive Errors",
            value=str(error_count),
            inline=True
        )
        
        embed.set_footer(
            text="Please check bot logs for more details"
        )
        
        return embed
    
    @staticmethod
    def _format_category_name(category: str) -> str:
        """
        Format category name for display.
        
        Args:
            category: Category identifier.
        
        Returns:
            str: Formatted category name.
        """
        return DiscordFormatter.CATEGORY_NAMES.get(category, "News")
